victorchall/EveryDream2trainer

- Train_Colab.ipynb
- train.py
- train_colab.py
this train_colab.py works around the keyboard and progress bar issues while allowing Colab to run
> a colab edition capable of running on free teir

- train.py
Still need to have a log_writer with wandb
> Fix wandb setup

- Train_Colab.ipynb
> Added a simple cell for Inference testing of diffusers

- train.py
logging.ERROR is an int, not a function
> fix `'int' object is not callable` warning

- Train_Runpod.ipynb
Sm86 (A5000/3090/4090/etc) support was fixed in [this commit](https://github.com/facebookresearch/xformers/commit/615175f6082afcb91e72bf277ea9d3c722cc4a11)
The v0.0.16 pypi wheel works fine for A100s
> Build working version of xformers for A5000/3090s

- train.json
change "rated_dataset_target_dropout_rate:" to "rated_dataset_target_dropout_percent:"
> Bug Squashed

- Train_JupyterLab.ipynb
- doc/SETUP.md
- installers/Runpod.ipynb
...into RunPod-specific installer and generic training notebook. This should make it easier to support other providers.
Also fixed the progress bars.
> Split Train_Runpod.ipynb

- train.py
> restore saving on error

- data/every_dream_validation.py
- train.py
- utils/split_dataset.py
Also fix `utils/split_dataset` and add a pre-train validation baseline run
> Fix validation division by zero

- data/every_dream_validation.py
- utils/sample_generator.py
also decouple validation count from batch size to ensure consistent behaviour with different batch sizes
> actually use the validation random seed

- data/every_dream_validation.py
Make validation loss graph relative to 0=start of training, instead of some random starting loss.
Also enforce more random reproducibility (there's still some source of random i can't eliminate)
> make validation more comparable across runs

- Train_JupyterLab.ipynb
- data/dataset.py
- data/every_dream.py
- data/image_train_item.py
- data/resolver.py
- docker/Dockerfile
- docker/requirements.txt
- test/test_data_resolver.py
- test/test_dataset.py
- test/test_image_train_item.py
- utils/fs_helpers.py
Add support for:
* flip_p.txt
* cond_dropout.txt
* local.yaml consolidated config (including default captions)
* global.yaml consolidated config which applies recursively to subfolders
* flip_p, and cond_dropout config per image
* manifest.json with full image-level configuration
> Add support for enhanced dataset configuration

- doc/DATA.md
Preview [here](https://github.com/qslug/EveryDream2trainer/blob/config-fix/doc/DATA.md)
> Update docs around configuring captions and other image config

- Train_JupyterLab.ipynb
- data/dataset.py
- docker/Dockerfile
- docker/requirements-runtime.txt
- docker/start.sh
- test/test_data_resolver.py
- test/test_dataset.py
* StopIteration error should be limited to filenames starting with an `_`
* `start.sh` should do something useful by default
* Add ul/dl speedtest cell to notebook
* Add lion to `requirements.txt`
> Mixed mode captioning and QoL tweaks

- docker/requirements-runtime.txt
- train.py
- utils/sample_generator.py
- windows_setup.cmd
Introduces dependency on `compel` which also allows weighting prompts (though we probably don't want to be doing that in samples)
> Respect clip_skip when generating samples

- data/image_train_item.py
PIL lazy loads pixel data, so image size can be accessed without loading the full image. This commit makes it so only image size and EXIF metadata are fetched from disk, speeding up the preload stage while still supporting transposing images.
> Speed up image preloading by not loading pixel data

- optimizer/optimizers.py
- requirements.txt
Adds (essentially) parameterless DoWG optimizer in the form of ScalarDoWG (scalar_dowg). There is CoordinateDoWG, but I have disabled that in ED2 for the time being as it is meta-stable at best with SD. I will try to find more on that front.
Clip *can* be adjusted as an optimizer config. but the only other value worth considering is 1. .5 is pretty much the perfect balance for any adaptive algorithm, and 1 just turns it off otherwise.
> Dowg optimizer

- train.py
This one has been bugging me for a hot minute.
> Fix spelling error

- .gitignore
- doc/SETUP.md
- docker-compose.yml
- docker/Dockerfile
- docker/start.sh
This makes it a lot easier to use locally on docker, and a lot easier to move files in/out, as well as save notebooks.
> Add docker compose file

- train.py
- utils/sample_generator.py
fix ZTSNR sample generation and diffusers output
* use CFG rescaling when generating samples
* save original beta schedule (`"trained_betas": null`) rather than the ZTSNR tweaked betas, which break Karras scheduling at inference with diffusers
> fixes for ZTSNR training

- doc/ADVANCED_TWEAKING.md
- train.json
- train.py
- trainSD21.json
- utils/sample_generator.py
This PR introduces new features:
1. **EMA decay support**: 
- EMA model updated at specified intervals.
- Option to store on CPU to conserve VRAM.
- Generation of samples, checkpoints, and diffusers now support both EMA and non-EMA models.
- Introduced `ema_decay_resume_model` for EMA model loading.
2. **min_snr_gamma**: 
- Aims to improve convergence speed. More details: [arxiv.org/abs/2303.09556](https://arxiv.org/abs/2303.09556).
3. **Settings loading every epoch**: 
- 'train.json' reloaded at the onset of each epoch.
4. **Separation of zero terminal SNR**: 
- Now independent from `zero_frequency_noise_ratio`.
5. **Configuration & Documentation Updates**:
- Added new parameters to configuration files.
- Updated `ADVANCED_TWEAKING.md` with relevant descriptions.
> EMA decay, min-SNR-gamma, settings loading every epoch, zero terminal SNR separation from ZFN.

- train.py
Hey! I just pulled the last changes after realize that the models were not being saved on each epoch.
Lookis like now the models are created but they are ignoring the target directory (`save_ckpt_dir`).
Maye you forgot to change one of the arguments?
Regards!
> Fix save_ckpt_dir not being honored when saving model

- data/dataset.py
- data/every_dream.py
- data/image_train_item.py
- train.py
put a file loss_scale.txt containing a single float into a folder of training examples to apply the float to the losses.
for example, use -1 to treat the examples as "negative" examples (i.e. the trainer should push the model away from these images).
todo:
> add loss_scale.txt

- train.py
I was getting an error when using the min SNR gamma option.
Not sure if this is the right approach but It works on my machine ✌️
> Fix device mismatch when using min snr gamma option

- doc/PLUGINS.md
Mostly formatting and readability
> Quick edits to improve PLUGINS.md

- doc/ADVANCED_TWEAKING.md
- optimizer/adacoor.py
- optimizer/optimizers.py
- train.json
- train.py
1. Added AdaCoor optimizer.
2. Added pyramid noise.
> New optimizer and pyramid noise

- caption.py
BLIP2 was loading into system RAM rather than VRAM for me. I found that adding argument "device_map=device" forces it to load the entire model onto the specified device. I tested it for cuda and cpu successfully.
GIT was failing because its processor returns a BatchEncoding and its method to() only accepts one device parameter, so I removed the second dtype parameter and it worked. I don't see how BLIP2 is different, but it works with both parameters, so I left it to avoid breaking any functionality.
> BLIP2 and GIT updates
