victorchall/EveryDream2trainer

README.md
data/data_loader.py
data/every_dream.py
data/image_train_item.py
doc/SHUFFLING_TAGS.md

This PR implements a strategy to shuffle caption tags taking weight definitions into account and the functionality to read caption definitions from YAML files, for fine granted definitions of weights.

Support more control regarding caption tag shuffeling using yaml files

---

data/data_loader.py

The current check for file name extensions to find images within the data_root directory is case sensetive and images with .JPG or .PNG will be ignored.
I agree to the CLS as described under:
https://github.com/victorchall/EveryDream2trainer/blob/main/doc/EveryDream_CLA.txt

Make file name extension check case insensitive, so .JPG or .PNG file will be detected

---

data/data_loader.py
data/every_dream.py
data/image_train_item.py
train.json
train.py

First: I agree to the Contributor License Agreement
This is the second part of the dynamization of training data through a training session.
This PR focuses on skewing the selection of images to train to higher rated images.
This is done by leaving out less favorabel images in later epochs, at an increasing rate.
The result is that the model has seen more favorabel images more often and more recently at the end of the training session.
To accomplish this the user can define a rating per image in the YAML file.
The rating of one image is compared to the ratings of the other images. A rating twice as high then the rating of another image would result in twice as high a chance to be picked in the later stages of the training.
The second parameter is the target dropout rate in percent at the …

Implemented system to train on a subset of the dataset, favoring higher rated images

---

data/image_train_item.py

After the refactoring, the tag was added twice to the caption

Bugfix: Adding same Tag twice to Caption

---

Train_Colab.ipynb

fixed link to a100 xformers
removed train_colab link to my github
added getyaml to dependencies cell previously this was tied to model download however if a user brings their own ckpt from somewhere else then they would not have the yamml for conversion
added pip install triton to dependencies cell

a100 xformer link

---

train.py

allows editing/changes to sample prompts while generation is running without having to restart

re-read sample prompts txt file every generation

---

data/data_loader.py
data/every_dream.py
data/resolver.py
test/test_data_resolver.py
train.py

This patch
* passes the configuration (`argparse.Namespace`) to the resolver,
* pushes the DLMA code into the main function,
* makes DLMA take a `list[ImageTrainItem]` instead of `data_root`,
* makes `EveryDreamBatch` take a DLMA instance instead of `data_root`,
* moves `write_batch_schedule` to `train.py`,
* allows `data_root` to be a list for conveniently specifying a many directories and/or JSON files.
By doing these things, both `EveryDreamBatch` and DLMA can be free from data resolution logic, reporting errors, and logging undersized image information. The arguments passed down to EDB and DLMA are the essential ones they need. This should also mean that there is no need for the data loader singleton. If I am wrong about that, I can put the `dls` initialization back in.

Push DLMA into `main`, improvements to `data.resolve`

---

Train_Colab.ipynb

Prior version of Xformers is no longer available switching link to last stable release.
https://pypi.org/project/xformers/#history
Tested!

Xformer update

---

data/data_loader.py
data/every_dream.py
data/every_dream_validation.py
data/image_train_item.py
data/resolver.py
train.py

There's some changes in here to how multiplier.txt is applied. 
Mainly, the logic has been simplified and moved to runtime rather than load time. On `DataLoaderMultiAspect` multipliers are lazily applied in `__pick_multiplied_set()`, rather than being pre-baked into `prepared_train_data`. The main implication of this is that for fractional multipliers, EveryDream will now train with a different random subset of the folder each epoch, rather than picking the subset once on load and then re-using the same subset every epoch.
I have not extensively tested this - please check that it works as expected with fractional and also >1 multipliers before merging.

Fix multiplier issues with validation, and refactor validation logic

---

utils/convert_original_stable_diffusion_to_diffusers.py

checkpoints converted from diffusers don't appear to have the "cond_stage_model.model.text_projection" key. The shape information can be obtained from the checkpoint values directly.

fix roundtrip text_encoder

---

doc/LOGGING.md
train.py
utils/sample_generator.py

Preserves existing functionality while adding new fun stuff.
Example `sample_prompts.json` (documented in `LOGGING.MD`)
```json
{
"batch_size": 3,
"seed": 555,
"cfgs": [7, 4],
"scheduler": "dpm++",
"num_inference_steps": 15,
"show_progress_bars": true,
"samples": [
{
"prompt": "ted bennet and a man sitting on a sofa with a kitchen in the background",
"negative_prompt": "distorted, deformed"
},
{
"prompt": "a photograph of ted bennet riding a bicycle",
"seed": -1
},
{
"random_caption": true,
"size": [640, 384]
}
]
}
```

Refactor sample generation and introduce sample_prompts.json

---

train.py
utils/huggingface_downloader.py

this is better than using `download_snapshot` because it automatically knows how to handle `.safetensors`

use StableDiffusionPipeline.from_pretrained() to download HF models

---

data/every_dream_validation.py
data/resolver.py
doc/LOGGING.md
doc/OPTIMIZER.md
optimizer.json
train.py
utils/sample_generator.py

* Implement different LR for the text encoder. Control with `text_encoder_lr_scale` in `optimizer.json` (default=1).
i also started making some small tweaks to the sample generator and it kinda got away on me:
* Tidy up validation and sample generator progress bars by properly passing `position` and `leave=False` arguments to `tqdm`.
* Add `aspect_ratio` feature to samples config, to automatically determine an appropriate aspect ratio for the training size. 
* Add `generate_samples_every_n_steps` and `generate_pretrain_samples` to samples config file.
* Improve sample generation logging.
* Update docs

Separate text encoder LR; logging & pbar improvements; misc sample generator tweaks

---

Train_Colab.ipynb

Discord complaints of last.ckpt not appear may be due to auto disconnect only waiting 3 seconds after training this updates it to 40 which is more then enough time to save to the Gdrive (takes about 28 seconds). This will be safe to accept with out further testing due to only timer being changed.

update sleep timer for disconnet

---

data/dataset.py
test/test_dataset.py

As of Python 3.7 (and CPython 3.6), standard `dict` is [guaranteed to preserve order](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6)
As of Python 3.9, the binary "or" operator `|` [has been defined to concatenate dictionaries](https://stackoverflow.com/questions/9819602/union-of-dict-objects-in-python). (A new, concrete dictionary is eagerly created)

Retain original tag order when parsing captions

---

data/every_dream.py
data/image_train_item.py

set # of data loaders by the min of batch size or cpu count, do not do an expensive rgb image conversion when only loading image metadata

image preloading and data loading optimizations. 

---

utils/convert_original_stable_diffusion_to_diffusers.py

Fixes weight conversion for some weights that are produced by AUTO1111 UI which have different layer order for output modules (bias layer before weight layer). Similar to https://github.com/ratwithacompiler/diffusers_stablediff_conversion/commit/f3434631ad0e480e153c2c9ec02a28fafdda764a

Convert order fix

---

data/aspects.py
data/data_loader.py
train.py

Log a warning and suggestion to reduce batch size or add more images if an aspect ratio bucket's runt size causes the effective multiplier for images at that aspect ratio to be >1.5

warn on chronically underfilled aspect ratio buckets

---

docker/Dockerfile

Specifically LD_LIBRARY_PATH, but everything with an `_` in the name will be exported. Verified to work via on an SSH-only Vast instance

Export ENV vars for Vast.ai SSH

---

optimizer/optimizers.py

currently, if you're using AMP clip_grad_scale is applied to the scaled gradients. this means that you have to pass values like `1e5` or `1e6` for cilp_grad_scale (depending on the state of the AMP scaler), rather than the common/expected `1.0`. moreover, because gradient scaling is dynamic, it's likely the value you pick won't be correct.
this PR makes `--clip_grad_scale` operate on the unscaled gradients instead, meaning you can pass the common/expected value of `1.0` and it will do the right thing (instead of effectively halting training).

correctly apply `clip_grad_scale` to unscaled gradients

---

data/aspects.py
data/data_loader.py
data/dataset.py
data/image_train_item.py
doc/ADVANCED_TWEAKING.md
test/test_first_fit_decreasing.py
train.py
utils/first_fit_decreasing.py

Add a `batch_id.txt` file containing a batch id string to a subfolder (or add a `batch_id` key to `local.yaml`) to cause images sharing the same batch id to be processed together.

User defined batching

---

data/data_loader.py
data/every_dream_validation.py
utils/sample_generator.py

a few improvements to batch shuffling and validation
* fix a bug where an empty `samples.txt` was not populated with random samples
* fix a shuffling bug handling rare aspect ratios: non-named batches are now shuffled better, preventing clustering of rare aspect ratios at the end of the epoch (symptom: "random caption" samples were often repeated if sampling steps == epoch length)
* better named batch runt handling: named batch runts in a given epoch are dynamically demoted to the DEFAULT_BATCH_ID for that epoch, preventing over-duplication
* permit `null` for `manual_data_root` for `manual` validation if there are entries `extra_manual_datasets`
* when using `extra_manual_datasets`, also log a mean of all validation losses to `loss/_all_val_combined`

misc small fixes

---

optimizer.json
optimizer/optimizers.py
train.py

with this patch you can
* pass `--no_prepend_last` to prevent ED from renaming the last save to `last-<name>`
* pass `--no_save_ckpt` to disable ckpt saving (diffusers format models are still saved)
* add `"apply_grad_scaler_step_tweaks": false` to optimizer.json to prevent ED from tweaking the grad scaling (which seems to be disruptive when training SD2)
also, the final epoch save is low labelled `ep<max_epochs>` rather than `ep<max_epochs-1>`

same flags Damian would like

---

doc/ADVANCED_TWEAKING.md
doc/OPTIMIZER.md
optimizer.json
optimizer/optimizers.py
optimizerSD21.json

no more weird negative arguments, just set `"unfreeze_last_n_layers": 2` in optimizer.json:
```
"text_encoder_freezing": {
"unfreeze_last_n_layers": 2
}
```
`freeze_embeddings` and `freeze_final_layer_norm` are still recognized but are no longer necessary as they're automatically set.

simplify freezing text encoder layers config

---

data/image_train_item.py

The original function has a couple of problems:
1. The image.crop is done on values that are not integers, and it rounds them internally. cropped_image.resize is done on values after they are summed up and truncated to an integer. Usually, there is a 1-pixel difference between crop and resize in every dimension most of the time, which stretches images and can introduce stretching patterns.
2. cropped_image.resize done according to an aspect ratio of the cropped image - it's unnecessary.
The change simplifies the function, prevents stretching, prevents unnecessary resizing, and prevents cropping more pixels than what crop_jitter value allows.
Tested with a dataset of 27,000 images, with 10 epochs training.

Refactored the _percent_random_crop function to prevent unnecessary stretch.

---

data/every_dream.py
data/image_train_item.py
doc/ADVANCED_TWEAKING.md
doc/SHUFFLING_TAGS.md
train.py

Hey! I realize that I have a dataset with very long captions, so I decided to shuffle the tags on training.
The problem is that the most important tags are on the begining (and I'm not using weights) so I decided to add this feature for keeping the first N tags after the first tag (aka the main prompt) and just shuffle the rest of them, so If some of the randomized tags get out of the 75 tokens limits is not a big deal.
Not sure if this is worth for somebody. I think, the Kohya trainer have the --keep_tokens arg to prevent those shuffling.
Hope you find it useful!
Thanks for this amazing tool!

Add --keep_tags to keep first N tags fixed on shuffle

---

data/image_train_item.py
test/test_image_train_item.py

This PR addresses two issues related to image size detection and warning messages:
- Eliminates the warning message when the target image dimensions align with the training resolution.
- Correctly writes the image dimensions instead of `None` for undersized images.
Prior to this fix, the system incorrectly flags a target image as "undersized" when its dimensions are exactly the same as the training resolution. For instance, with a training resolution of 512, a 512x512 target image triggers the following entry in the undersize log:
```
... target_image.png with size: None is smaller than target size: [512, 512]
```

Fix Inaccuracies in Image Size Validation and Warning Display

---

train.py

unet needs to be in train() mode for gradient checkpointing to work

prevent OOM with disabled unet when gradient checkpointing is enabled

---

caption_cog.py

fixs this
File "D:\EveryDream2trainer\caption_cog.py", line 143, in main
f.write(caption)
UnicodeEncodeError: 'cp949' codec can't encode character '\xe9' in position 333: illegal multibyte sequence

Fixs error when translated caption contains an unusual byte

---

optimizer/optimizers.py
plugins/plugins.py
plugins/textual_inversion.json
plugins/textual_inversion.py
plugins/textual_inversion_loader.json
train.py
utils/sample_generator.py

With this plugin you can target specific token embeddings in the text encoder, and/or add new ones. The embeddings get written into the model's text encoder and saved out - not the most efficient way to share them, but useful if you want to laser-focus training of specific or custom tokens in your model.
Documentation (such as it is) is in plugins/textual_inversion.py. TL;DR is - first edit plugins/textual_inversion.json to set up your tokens and initialization states. enable text encoder training and disable unet training. then edit optimizer.json to freeze all TE layers and TE final layer norm. the plugin checks for sane config when it's used.
you'll want to use a very high LR for the TE. my last test worked best at 2e-2.

Feat textual inversion plugin v2
